version: '2'
services:
  volunteer-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/volunteer/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=volunteer
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
